export default ['Ablekuma central municipal', 'Ablekuma north municipal', 'Ablekuma west municipal', 'Accra metropolitan', 'Ada east district', 'Ada west district', 'Adentan municipal', 'Afadzato south district', 'Agona east district', 'Agona west municipal', 'Ahafo ano north municipal',
    'Ahafo ano south east district',
    'Ahafo ano south west district',
    'Ahanta west municipal',
    'Ajumako/enyan/essiam district',
    'Akatsi north district', 'Akatsi south district', 'Akrofuom district', 'Akuapem north municipal', 'Akuapem south district', 'Amansie central district', 'Amansie south district', 'Amansie west district', 'Amenfi central district', 'Amenfi east municipal', 'Amenfi west municipal',
    'Asante akim central municipal',
    'Asante akim north district',
    'Asante akim south municipal',
    'Asokore mampong municipal', 'Assin foso municipal', 'Assin north district', 'Assin south district', 'Atebubu-amantin municipal', 'Atwima kwanwoma district', 'Atwima mponua district', 'Atwima nwabiagya municipal', 'Ayawaso central municipal', 'Ayawaso east municipal', 'Ayawaso north municipal', 'Ayawaso west municipal', 'Banda district', 'Bantama municipal', 'Berekum east municipal', 'Berekum west district',
    'Bibiani-anhwiaso-bekwai municipal',
    'Bia east district', 'Bia west district', 'Bimbilla municipal', 'Birim central municipal', 'Birim north district', 'Birim south district', 'Bodi district', 'Bolgatanga east district', 'Bolgatanga municipal', 'Bongo district', 'Bosome freho district', 'Bosomtwe district', 'Builsa north municipal', 'Builsa south district',
    'Bunkpurugu-nyankpanduri district',
    'Cape coast metropolitan', 'Central gonja district', 'Chereponi district', 'Dormaa central municipal', 'Dormaa east district', 'Dormaa west district', 'East gonja municipal', 'East mamprusi municipal',
    'Effia-kwesimintsim municipal',
    'Effutu municipal', 'Ejisu municipal',
    'Ejura-sekyedumase municipal',
    'Ellembelle district', 'Fanteakwa north district', 'Fanteakwa south district', 'Ga central municipal', 'Ga east municipal', 'Ga north municipal', 'Ga south municipal', 'Ga west municipal', 'Garu district', 'Gomoa central district', 'Gomoa east district', 'Gomoa west district', 'Ho municipal', 'Hohoe municipal', 'Jaman north district', 'Jaman south municipal', 'Jomoro municipal', 'Juaboso district', 'Juaben municipal', 'Kade municipal', 'Kadjebi district', 'Keta municipal', 'Ketu north municipal', 'Ketu south municipal', 'Kintampo municipal', 'Kintampo north municipal', 'Kintampo south district', 'Kpone-katamanso municipal', 'Krachi east municipal', 'Krachi nchumuru district', 'Krachi west district', 'Krowor municipal', 'Kumasi metropolitan', 'Kwabre east municipal',
    'Kwahu afram plains north district',
    'Kwahu afram plains south district',
    'Kwahu east district', 'Kwahu south district', 'Kwahu west municipal', 'La dade-kotopon municipal',
    'La nkwantanang madina municipal',
    'Lambussie karni district', 'Lawra municipal', 'Ledzokuku municipal',
    'Lower manya krobo municipal',
    'Mampong municipal', 'Mpohor district', 'Nadowli-kaleo district', 'Nandom municipal', 'Nanumba north municipal', 'Nanumba south district', 'Nkoranza north district', 'Nkoranza south municipal', 'North east gonja district', 'North east gonja municipal', 'North dayi district', 'North gonja district', 'North tongu district', 'Nsawam adoagyiri municipal', 'Nungua municipal', 'Nzema east municipal', 'Obuasi municipal', 'Offinso municipal', 'Offinso north district', 'Offinso south municipal', 'Okaikwei north municipal',
    'Prestea-huni valley municipal',
    'Pru east district', 'Pru west district', 'Saboba district', 'Salaga north district', 'Salaga south district', 'Sefwi akontombra district', 'Sefwi wiawso municipal',
    'Sekondi-takoradi metropolitan',
    'Sene east district', 'Sene west district', 'Shai osudoku district', 'Sissala east municipal', 'Sissala west district', 'South dayi district', 'South tongu district', 'Suaman district', 'Suhum municipal', 'Sunyani municipal', 'Sunyani west municipal', 'Talensi district', 'Tarkwa-nsuaem municipal', 'Techiman municipal', 'Techiman north district', 'Tema metropolitan', 'Tema west municipal', 'Tain district', 'Tano north municipal', 'Tano south municipal', 'Tatale sanguli district', 'Tepa municipal', 'Tolon district', 'Twifo ati-morkwa district',
    'Twifo-heman-lower denkyira district',
    'Upper denkyira east municipal',
    'Upper denkyira west district',
    'Upper west akim district', 'Wa east district', 'Wa municipal', 'Wa west district',
    'Wassa amenfi east municipal',
    'Wassa amenfi west municipal',
    'Wassa east district', 'Wassa west municipal', 'West akim municipal', 'West gonja district', 'West mamprusi municipal', 'Wulensi municipal', 'Yendi municipal', 'Zabzugu district', 'Zuarungu municipal',
]